### ISSUE TITLE
Client not launching on Ubuntu 24.04

### ISSUE THREAD

**Issue by purekillma** [colinmarc/magic-mirror#14]
Client does not launch on any version of the client (Test 1.0, 1.1, 1.2)

I keep getting this error 

`/mmclient: error while loading shared libraries: libavutil.so.56: cannot open shared object file: No such file or directory`

FFMPEG version is 6.1.1

`libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
`

Here is the version of libavutil which is 58 which got installed when installed ffmpeg

**Comment by colinmarc** [comment]
Looks like CI is installing the wrong version of ffmpeg: https://github.com/colinmarc/magic-mirror/actions/runs/8957916106/job/24601542219#step:3:612

I'll fix this and push another release. In the meantime, the solution is just to build the client from source. I included build instructions here: 

https://github.com/colinmarc/magic-mirror/blob/main/BUILD.md

**Comment by colinmarc** [comment]
This may have to wait until 24.04 runners are available in github actions (supposedly mid-May). I checked out a few other options for installing ffmpeg and they were too high effort.

**Comment by colinmarc** [comment]
This should be fixed.
